# Generated by Django 3.1.7 on 2021-04-05 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210405_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='cover',
        ),
    ]
